"""Cookies in the Netscape format: the same file curl and browser extensions use."""

from __future__ import annotations

from pathlib import Path

import curlpro
import pytest
from curlpro.cookies import format_netscape, parse_netscape

REPO = Path(__file__).resolve().parents[2]


@pytest.fixture(scope="session", autouse=True)
def _profiles():
    curlpro.load_profiles(REPO / "profiles")


CURL_FILE = """# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.example.com\tTRUE\t/\tTRUE\t1893456000\tsid\tabc123
#HttpOnly_.example.com\tTRUE\t/api\tFALSE\t0\ttoken\tsecret
www.example.com\tFALSE\t/\tFALSE\t1893456000\tpref\tdark
"""


def test_reads_a_file_written_by_curl():
    cookies = parse_netscape(CURL_FILE)
    assert [c["name"] for c in cookies] == ["sid", "token", "pref"]

    sid, token, pref = cookies
    assert sid["domain"] == ".example.com" and sid["secure"] is True
    assert sid["expires"] == 1893456000 and sid["http_only"] is False
    # The #HttpOnly_ prefix is not a comment: the line must be read with it stripped.
    assert token["http_only"] is True and token["path"] == "/api"
    assert token["expires"] == 0, "zero means a session cookie"
    assert pref["secure"] is False and pref["value"] == "dark"


def test_comments_and_blank_lines_are_skipped():
    assert parse_netscape("# a comment only\n\n   \n") == []


def test_missing_value_column_is_an_empty_value():
    """Editors trim an empty value together with its tab."""
    cookies = parse_netscape(".example.com\tTRUE\t/\tFALSE\t0\tempty")
    assert cookies[0]["name"] == "empty" and cookies[0]["value"] == ""


def test_broken_line_names_its_number():
    with pytest.raises(ValueError, match="line 2"):
        parse_netscape(".a.com\tTRUE\t/\tFALSE\t0\tn\tv\ngarbage\n")

    with pytest.raises(ValueError, match="expiry"):
        parse_netscape(".a.com\tTRUE\t/\tFALSE\ttomorrow\tn\tv")


def test_round_trip_keeps_the_essentials():
    """Domain, path, expiry and flags must survive the round trip through a file."""
    with curlpro.Session() as s:
        s.cookies.set("sid", "abc", domain="example.com", expires=1893456000,
                      secure=True, http_only=True)
        s.cookies.set("plain", "1", domain="example.org", path="/api")
        text = s.cookies.to_netscape()

    with curlpro.Session() as s:
        s.cookies.load(parse_netscape(text))
        by_name = {c.name: c for c in s.cookies.all()}

    sid = by_name["sid"]
    assert sid.value == "abc" and sid.expires == 1893456000
    assert sid["secure"] is True and sid["http_only"] is True
    # The core strips the dot: inside, the domain is stored without it.
    assert sid.domain == "example.com"
    assert by_name["plain"].path == "/api"


def test_export_marks_domain_cookies():
    """Our cookies also go to subdomains, so the file gets a dot and TRUE."""
    text = format_netscape([{
        "name": "a", "value": "1", "domain": "example.com",
        "path": "/", "expires": 0, "secure": False, "http_only": False,
    }])
    row = [ln for ln in text.splitlines() if not ln.startswith("#") and ln][0]
    assert row.split("\t")[:2] == [".example.com", "TRUE"]


def test_http_only_survives_the_file():
    text = format_netscape([{
        "name": "t", "value": "x", "domain": ".example.com",
        "path": "/", "expires": 0, "secure": False, "http_only": True,
    }])
    assert "#HttpOnly_.example.com" in text
    assert parse_netscape(text)[0]["http_only"] is True


def test_save_and_load_file_detect_the_format(tmp_path):
    """load_file looks at the content: a cookies.txt may be named anything."""
    path = tmp_path / "jar"
    with curlpro.Session() as s:
        s.cookies.set("sid", "abc", domain="example.com")
        s.cookies.save_netscape(path)

    with curlpro.Session() as s:
        s.cookies.load_file(path)
        assert s.cookies["sid"] == "abc"

    # JSON for the same purpose is still read by the same method.
    js = tmp_path / "state.json"
    with curlpro.Session() as s:
        s.cookies.set("sid", "json", domain="example.com")
        s.cookies.save(js)
    with curlpro.Session() as s:
        s.cookies.load_file(js)
        assert s.cookies["sid"] == "json"


def test_load_netscape_refuses_json(tmp_path):
    """An explicit call must complain about a foreign format rather than stay quiet."""
    path = tmp_path / "state.json"
    path.write_text('[{"name": "a", "value": "1", "domain": "example.com"}]',
                    encoding="utf-8")
    with pytest.raises(ValueError):
        with curlpro.Session() as s:
            s.cookies.load_netscape(path)


def test_missing_file_is_not_an_error(tmp_path):
    with curlpro.Session() as s:
        s.cookies.load_netscape(tmp_path / "no-such-file.txt")
        s.cookies.load_file(tmp_path / "no-such-file.json")
        assert len(s.cookies) == 0
